In [1]:
import _pickle as pkl
import csv
import sys
import pandas as pd
import pandas
import os

def list_dir(path):
    source_path_dict = {}
    dirs = os.listdir(path)
    for files in dirs:
        try:
            sub_dirs = os.listdir(path + "/" + files)
            for file_name in sub_dirs:
                if (file_name.endswith('parquet') or file_name.endswith('csv')):
                    source_path_dict[files] = os.path.join(
                        path, files, file_name)
        except:
            source_path_dict[files] = os.path.join(path, files)
    return source_path_dict

def load_df(filename):
    if "pkl" in filename:
        return pandas.read_pickle(filename)
    else:
        return pandas.read_csv(filename, sep='\t', header=None)

In [2]:
local_prefix = "/mnt/nvme2/chendi/BlueWhale/x-deeplearning/xdl-algorithm-solution/DIEN/data/modin_output"

source_path_dict = list_dir(local_prefix + '/')
cat_voc = load_df(source_path_dict["cat_voc.pkl"])
mid_voc = load_df(source_path_dict["mid_voc.pkl"])
uid_voc = load_df(source_path_dict["uid_voc.pkl"])
train = load_df(source_path_dict["local_train_splitByUser.csv"])
test = load_df(source_path_dict["local_test_splitByUser.csv"])

/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3338: DtypeWarning: Columns (0,3,4) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

In [3]:
train

,0,1,2,3,4,5,6,7
0,label,userID,itemID,rating,rtime,cat,item_history,cat_history
1,0,A00003322NZ9C82Y46DFN,1565632559,5.0,1403740800,Books,0957544901,Books
2,1,A00003322NZ9C82Y46DFN,0786903945,5.0,1403740800,Books,0957544901,Books
3,0,A00005181SC9PSCD58LCG,B00GC30EGE,5.0,1400025600,Historical,1492111619^076278038X^0062023144,Books^Books^Books
4,1,A00005181SC9PSCD58LCG,0800720024,5.0,1400025600,Books,1492111619^076278038X^0062023144,Books^Books^Books
...,...,...,...,...,...,...,...,...
14451114,0,AZZZYCR4NZADZ,0313360510,5.0,1182124800,Books,NaN,NaN
14451115,1,AZZZYCR4NZADZ,0738710423,5.0,1180828800,Books,NaN,NaN
14451116,1,AZZZYCR4NZADZ,0099472287,5.0,1182124800,Books,NaN,NaN
14451117,0,AZZZZCVMZCKUJ,0793519799,2.0,1357689600,Books,NaN,NaN
14451118,1,AZZZZCVMZCKUJ,1401323464,2.0,1357689600,Books,NaN,NaN

In [5]:
local_prefix = "/mnt/nvme2/chendi/BlueWhale/recsys_preprocessing/dien_preprocessing_pandas/pickle_files/"

source_path_dict = list_dir(local_prefix + '/')
cat = load_df(source_path_dict["cat.pkl"])
asin = load_df(source_path_dict["asin.pkl"])
userID = load_df(source_path_dict["userID.pkl"])
itemID = load_df(source_path_dict["itemID.pkl"])
rtime = load_df(source_path_dict["rtime.pkl"])